# Javascript Node CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-javascript/ for more details

version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6.10

    working_directory: ~/repo

    steps:
      - checkout

      - run: sudo apt-get install libsecret-1-dev
      - run: sudo npm install -g serverless

      - run: echo -e "$NPM_USER\n$NPM_PASS\n$NPM_EMAIL" | npm login

      - restore_cache:
          keys:
            - aws-node-modules-{{ arch }}-{{ .Branch }}-{{ checksum "~/repo/aws/package.json" }}

      - run:
          command: npm install
          working_directory: ~/repo/aws

      - save_cache:
          key: aws-node-modules-{{ arch }}-{{ .Branch }}-{{ checksum "~/repo/aws/package.json" }}
          paths:
            - ~/repo/aws/node_modules

      - run:
          command: npm test
          working_directory: ~/repo/aws

      - restore_cache:
          keys:
            - azure-node-modules-{{ arch }}-{{ .Branch }}-{{ checksum "~/repo/azure/package.json" }}

      - run:
          command: npm install
          working_directory: ~/repo/azure

      - save_cache:
          key: azure-node-modules-{{ arch }}-{{ .Branch }}-{{ checksum "~/repo/azure/package.json" }}
          paths:
            - ~/repo/azure/node_modules

      - run:
          command: npm test
          working_directory: ~/repo/azure

      - restore_cache:
          keys:
            - common-node-modules-{{ arch }}-{{ .Branch }}-{{ checksum "~/repo/common/package.json" }}

      - run:
          command: npm install
          working_directory: ~/repo/common

      - save_cache:
          key: common-node-modules-{{ arch }}-{{ .Branch }}-{{ checksum "~/repo/common/package.json" }}
          paths:
            - ~/repo/common/node_modules

      - run:
          command: npm test
          working_directory: ~/repo/common
