service: serverless-url-enrichment-aws

provider:
  name: aws
  runtime: nodejs6.10
  region: us-east-1
  stage: dev

package:
  exclude:
    - .gitignore
    - package.json
    - README.md
    - .git/**

plugins:
  - serverless-mocha-plugin

functions:
  webhook:
    handler: src/handlers.webhook
    name: ${self:provider.stage}-webhook-url-enrichment
    description: 'Webhook capture endpoint'
    events:
      - http:
          path: /
          method: post
          cors: true
  verify:
    handler: src/handlers.verify
    name: ${self:provider.stage}-verify-url-enrichment
    description: 'Webhook verification endpoint'
    events:
      - http:
          path: /
          method: get
          cors: true
